Feature/hu07 crear album
salchichongallo/miso-app-vinilos pull request #63
Opened 2024-11-20 19:59 UTC by leinerbarrios

2024-11-21 02:06 UTC, salchichongallo requested changes
Los comentarios más considerables serían: 1) Organizar la interfaz para que se logren ejecutar las pruebas de aceptación y 2) Revisar el formulario ya que no se habilita el botón de "Crear"

2024-11-21 02:06 UTC, salchichongallo commented on app/src/main/java/com/example/vinylsapp/album/utils/validators/ValidateAlbumName.kt
> +        name.length > 30 -> "máximo 30 caracteres."
¿Le agregamos la mayúscula a la `m`?

2024-11-21 02:06 UTC, salchichongallo commented on app/src/main/java/com/example/vinylsapp/album/models/AlbumNew.kt
> +data class AlbumNew(
Algunos campos son nulos, y me surge la duda respecto a los criterios de aceptación. De acuerdo a los criterios, parece que todos deben ser requeridos. ¿Podrías mirarlo?

2024-11-21 02:06 UTC, salchichongallo commented on app/src/main/java/com/example/vinylsapp/album/ui/elements/AlbumCreateErrorAlert.kt
> +        text = { Text("Ha ocurrido un error en el servidor, por favor intente nuevamente") },
Porfa agregar punto final al texto para que coincida con el diseño.

2024-11-21 02:06 UTC, salchichongallo commented on app/src/main/java/com/example/vinylsapp/album/ui/elements/AlbumCreateScreen.kt
> +                AlbumCreateSuccessAlert(navController, {
Agregando el nombre del parámetro al callback mejoraría un poco su legibilidad.

```
// Ejemplo
onOk = { ... }
```

2024-11-21 02:06 UTC, salchichongallo commented on app/src/main/java/com/example/vinylsapp/album/ui/elements/AlbumReleaseDateField.kt
> +            placeholder = { Text("DD/MM/YYYY") },
Actualizar placeholder YYYY por AAAA de acuerdo al diseño.

2024-11-21 02:06 UTC, salchichongallo commented on app/src/main/java/com/example/vinylsapp/album/ui/viewmodels/AlbumCreateViewModel.kt
> +class AlbumCreateViewModel(private val albumRepository: IAlbumRepository) : ViewModel() {
Este view model parece estar haciendo dos cosas:

1. Guarda el estado actual del formulario (valores y estado)
2. Guardado de nuevo álbum y manejo de éxito y fallo

¿Cómo luciría un view model solo para el formulario y este solo para el guardado?

2024-11-21 02:06 UTC, salchichongallo commented on app/src/main/java/com/example/vinylsapp/album/repositories/IAlbumRepository.kt
> +    suspend fun add(album: AlbumNew)
Actualmente las pruebas E2E fallan debido a que en el `AlbumRepositoryMock` haría falta implementar este método:

![image](https://github.com/user-attachments/assets/c2876cb1-0cf8-4a37-9801-1c06ff63e19e)

2024-11-21 02:06 UTC, salchichongallo commented on app/src/main/java/com/example/vinylsapp/album/ui/elements/AlbumGenreDropdown.kt
> +fun AlbumGenreDropdown(selectedGenre: AlbumGenre?, onGenreSelected: (AlbumGenre) -> Unit) {
Actualmente solo es posible desplegar el dropdown haciendo clic sobre el ícono en la parte derecha. ¿Sería posible desplegar al dar clic sobre todo el elemento?

![image](https://github.com/user-attachments/assets/f3f7e8b9-9b1f-42cb-b8ef-bc0ec34f6a63)

2024-11-21 02:06 UTC, salchichongallo commented on app/src/main/java/com/example/vinylsapp/album/ui/elements/AlbumReleaseDateField.kt
> +fun AlbumReleaseDateField(
No es posible seleccionar la fecha actual. Revisar criterio de aceptación:

![image](https://github.com/user-attachments/assets/0ecbd41d-91f3-48b5-8c74-cfbf66607205)

2024-11-21 02:06 UTC, salchichongallo commented on app/src/main/java/com/example/vinylsapp/album/ui/elements/AlbumCreateScreen.kt
> +fun AlbumCreateScreen(
El botón de "Crear" no es habilitado una vez se llenan todos los campos y son válidos.

Pasos para reproducir:

1. Generar error en algunos campos
2. Corregir los errores mostrados en los campos
3. Terminar de llenar el formulario
4. El botón no se habilita

Contexto relevante para la prueba:
- Información del dispositivo: Dispositivo virtual Pizel 7 API 33
- Red: La API está abajo

![image](https://github.com/user-attachments/assets/fd034c83-1f31-43c5-8082-d08df9adb13b)

2024-11-21 02:06 UTC, salchichongallo commented on app/src/main/java/com/example/vinylsapp/album/ui/elements/AlbumCreateScreen.kt
> +        bottomBar = { VinylsBottomAppBar(navController) },
El diseño nos indica que el bottom bar no debería ser visible. Considera removerlo.

2024-11-21 15:20 UTC, leinerbarrios commented on app/src/main/java/com/example/vinylsapp/album/models/AlbumNew.kt
> +data class AlbumNew(
Se establecen nulos para poder iniciar el formulario con los selectores y el DatePicker vacíos, de igual manera al intentar enviarse el formulario se valida que todos los campos estén diligenciados

2024-11-21 19:38 UTC, leinerbarrios commented on app/src/main/java/com/example/vinylsapp/album/ui/viewmodels/AlbumCreateViewModel.kt
> +class AlbumCreateViewModel(private val albumRepository: IAlbumRepository) : ViewModel() {
Entiendo que esta cargado de responsabilidades, sin embargo los demás ViewModels relacionados a creación también manejan estado de formularios, éxito y fallo de estos. Quizás este se ve más cargado por tener más campos. Lo que hice fue regirme del diagrama y manejar todo en un solo ViewModel.

2024-11-22 23:53 UTC, salchichongallo approved these changes

2024-11-23 00:00 UTC, merged